### ISSUE TITLE
'float' object has no attribute 'strip' 오류

### ISSUE THREAD

**Issue by backeung** [jiwon199/kobert_multiclass-classification#1]
안녕하세요,  '한국어_단발성_대화_데이터셋.xlsx'을 이용해서 동일한 방법으로 모델을 만들었을 때는 잘 완료되었습니다.
다만 제가 새로운 데이터셋으로 모델을 돌려보았는데, data_test(*3번째줄)에서 다음과 같은 오류가 발생합니다.
- 오류: 'float' object has no attribute 'strip' 

```
tok=tokenizer.tokenize
data_train = BERTDataset(train, 0, 1, tok,vocab, max_len, True, False)
data_test = BERTDataset(new_test, 0, 1, tok, vocab, max_len, True, False)
```
테스트 데이터 라벨링 완료한 사진입니다.
![image](https://user-images.githubusercontent.com/83320093/143022993-0f809163-c9e7-4603-a7e6-e40a3ec0f064.png)

다음과 같은 오류는 왜 발생하는지 혹시 아시나요?

**Comment by jiwon199** [comment]
> 안녕하세요, '한국어_단발성_대화_데이터셋.xlsx'을 이용해서 동일한 방법으로 모델을 만들었을 때는 잘 완료되었습니다. 다만 제가 새로운 데이터셋으로 모델을 돌려보았는데, data_test(*3번째줄)에서 다음과 같은 오류가 발생합니다.
> 
> * 오류: 'float' object has no attribute 'strip'
> 
> ```
> tok=tokenizer.tokenize
> data_train = BERTDataset(train, 0, 1, tok,vocab, max_len, True, False)
> data_test = BERTDataset(new_test, 0, 1, tok, vocab, max_len, True, False)
> ```
> 
> 테스트 데이터 라벨링 완료한 사진입니다. ![image](https://user-images.githubusercontent.com/83320093/143022993-0f809163-c9e7-4603-a7e6-e40a3ec0f064.png)
> 
> 다음과 같은 오류는 왜 발생하는지 혹시 아시나요?

제가 코드 돌려볼땐 본 적 없는 오류인데 데이터셋 엑셀파일의 문제가 아닌가 싶습니다... 제가 사용한 데이터셋은 아래와 비슷한 형식이고 sentence=문장 / emotion=클래스로 표시 되어있습니다
![image](https://user-images.githubusercontent.com/53902714/143024787-98c9507f-8951-4e91-a525-6e6b79b2e8dd.png)

**Comment by backeung** [comment]
넵!! 답변 감사합니다ㅠㅠ
올려주신 코드 도움 많이 되었습니다! 감사합니다!!

> > 안녕하세요, '한국어_단발성_대화_데이터셋.xlsx'을 이용해서 동일한 방법으로 모델을 만들었을 때는 잘 완료되었습니다. 다만 제가 새로운 데이터셋으로 모델을 돌려보았는데, data_test(*3번째줄)에서 다음과 같은 오류가 발생합니다.
> > 
> > * 오류: 'float' object has no attribute 'strip'
> > 
> > ```
> > tok=tokenizer.tokenize
> > data_train = BERTDataset(train, 0, 1, tok,vocab, max_len, True, False)
> > data_test = BERTDataset(new_test, 0, 1, tok, vocab, max_len, True, False)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 테스트 데이터 라벨링 완료한 사진입니다. ![image](https://user-images.githubusercontent.com/83320093/143022993-0f809163-c9e7-4603-a7e6-e40a3ec0f064.png)
> > 다음과 같은 오류는 왜 발생하는지 혹시 아시나요?
> 
> 제가 코드 돌려볼땐 본 적 없는 오류인데 데이터셋 엑셀파일의 문제가 아닌가 싶습니다... 제가 사용한 데이터셋은 아래와 비슷한 형식이고 sentence=문장 / emotion=클래스로 표시 되어있습니다 ![image](https://user-images.githubusercontent.com/53902714/143024787-98c9507f-8951-4e91-a525-6e6b79b2e8dd.png)
