### ISSUE TITLE
__init__() missing 1 required positional argument: 'pair'

### ISSUE THREAD

**Issue by backeung** [jiwon199/kobert_multiclass-classification#2]
안녕하세요, 지난번 문의 답변 주신 부분까지 해결했습니다:) 감사합니다!
다만 마지막에 새로운 리뷰 데이터셋의 라벨링을 진행하는 과정에서 다음과 같은 오류가 발생합니다.
오류: __init__() missing 1 required positional argument: 'pair'

제공해주신 마지막 코드도 그대로 실행해보았는데, 동일한 오류가 발생합니다.

혹시 제가 지금 잘못이해하고 하고 있는 거까요? ㅠㅠ

step1) 실행: 정상 작동
![image](https://user-images.githubusercontent.com/83320093/143399336-16f6f05a-0329-46de-bee2-03e7b20275f3.png)

step 2) sentence 입력 후 오류 발생
![image](https://user-images.githubusercontent.com/83320093/143399428-fb66f1fb-f903-4fef-9e12-a34597a77aea.png)

**Comment by jiwon199** [comment]
> 안녕하세요, 지난번 문의 답변 주신 부분까지 해결했습니다:) 감사합니다! 다만 마지막에 새로운 리뷰 데이터셋의 라벨링을 진행하는 과정에서 다음과 같은 오류가 발생합니다. 오류: **init**() missing 1 required positional argument: 'pair'
> 
> 제공해주신 마지막 코드도 그대로 실행해보았는데, 동일한 오류가 발생합니다.
> 
> 혹시 제가 지금 잘못이해하고 하고 있는 거까요? ㅠㅠ
> 
> step1) 실행: 정상 작동 ![image](https://user-images.githubusercontent.com/83320093/143399336-16f6f05a-0329-46de-bee2-03e7b20275f3.png)
> 
> step 2) sentence 입력 후 오류 발생 ![image](https://user-images.githubusercontent.com/83320093/143399428-fb66f1fb-f903-4fef-9e12-a34597a77aea.png)

predict 함수에서 틀린 곳이 있어서 수정하여 다시 올렸습니다. 마지막 두 셀 수정되었습니다!

**Comment by backeung** [comment]
> > 안녕하세요, 지난번 문의 답변 주신 부분까지 해결했습니다:) 감사합니다! 다만 마지막에 새로운 리뷰 데이터셋의 라벨링을 진행하는 과정에서 다음과 같은 오류가 발생합니다. 오류: **init**() missing 1 required positional argument: 'pair'
> > 제공해주신 마지막 코드도 그대로 실행해보았는데, 동일한 오류가 발생합니다.
> > 혹시 제가 지금 잘못이해하고 하고 있는 거까요? ㅠㅠ
> > step1) 실행: 정상 작동 ![image](https://user-images.githubusercontent.com/83320093/143399336-16f6f05a-0329-46de-bee2-03e7b20275f3.png)
> > step 2) sentence 입력 후 오류 발생 ![image](https://user-images.githubusercontent.com/83320093/143399428-fb66f1fb-f903-4fef-9e12-a34597a77aea.png)
> 
> predict 함수에서 틀린 곳이 있어서 수정하여 다시 올렸습니다. 마지막 두 셀 수정되었습니다!

해결되었습니다!! 감사합니다!!
